In [16]:
import pandas as pd

In [25]:
df = pd.read_csv('/Users/wuyoscar/Documents/Project/MOOP/Result/50Million-Result')

In [34]:

Problem_list = list(df.Problem.unique())
print(len(Problem_list))
result = df.sort_values('Problem').reset_index(drop =True)

10

In [27]:
result

,Problem,Alg_name,Iteration,Evaluations,Objectives,n_variables,xl,xu,exec_time,approx_nadir,solutions_shape,pop_size,path,image_location
0,KUR1,AGNOMEN,500000,50000000,2,2,[-5.05 -5.05],[5. 5.],13581.180147,[-7.21736514e+00 2.18325861e-11],100,100,/home/582/ow6835/MOOP/Result/KUR1/AGNOMEN_KUR1...,/home/582/ow6835/MOOP/Result/Images/KUR1/AGNOM...
1,KUR1,RNSGA2,500000,50000000,2,5,[-5.05 -5.05 -5.05 -5.05 -5.05],[5. 5. 5. 5. 5.],8727.708246,[-28.87092719 -11.90693593],100,100,/home/582/ow6835/MOOP/Result/KUR1/RNSGA2_KUR1_...,/home/582/ow6835/MOOP/Result/Images/KUR1/RNSGA...
2,KUR1,NSGA3,500000,50000000,2,2,[-5.05 -5.05],[5. 5.],6235.473179,[-7.22973258 0.07657397],117,100,/home/582/ow6835/MOOP/Result/KUR1/NSGA3_KUR1_2...,/home/582/ow6835/MOOP/Result/Images/KUR1/NSGA3...
3,KUR1,NSGA3,500000,50000000,2,3,[-5.05 -5.05 -5.05],[5. 5. 5.],6052.496338,[-14.64511541 -0.73148266],115,100,/home/582/ow6835/MOOP/Result/KUR1/NSGA3_KUR1_3...,/home/582/ow6835/MOOP/Result/Images/KUR1/NSGA3...
4,KUR1,NSGA3,500000,50000000,2,4,[-5.05 -5.05 -5.05 -5.05],[5. 5. 5. 5.],5977.766732,[-21.83803518 -0.60301657],114,100,/home/582/ow6835/MOOP/Result/KUR1/NSGA3_KUR1_4...,/home/582/ow6835/MOOP/Result/Images/KUR1/NSGA3...
5,KUR1,NSGA3,500000,50000000,2,5,[-5.05 -5.05 -5.05 -5.05 -5.05],[5. 5. 5. 5. 5.],5928.328999,[-29.29296344 -7.14727163],110,100,/home/582/ow6835/MOOP/Result/KUR1/NSGA3_KUR1_5...,/home/582/ow6835/MOOP/Result/Images/KUR1/NSGA3...
6,KUR1,RNSGA2,500000,50000000,2,2,[-5.05 -5.05],[5. 5.],9120.287959,[-7.21773178 -1.67613402],100,100,/home/582/ow6835/MOOP/Result/KUR1/RNSGA2_KUR1_...,/home/582/ow6835/MOOP/Result/Images/KUR1/RNSGA...
7,KUR1,AGNOMEN,500000,50000000,2,5,[-5.05 -5.05 -5.05 -5.05 -5.05],[5. 5. 5. 5. 5.],12762.316965,[-2.88707639e+01 1.23197724e-07],100,100,/home/582/ow6835/MOOP/Result/KUR1/AGNOMEN_KUR1...,/home/582/ow6835/MOOP/Result/Images/KUR1/AGNOM...
8,KUR1,AGNOMEN,500000,50000000,2,4,[-5.05 -5.05 -5.05 -5.05],[5. 5. 5. 5.],14054.189155,[-2.16531951e+01 1.12373815e-07],100,100,/home/582/ow6835/MOOP/Result/KUR1/AGNOMEN_KUR1...,/home/582/ow6835/MOOP/Result/Images/KUR1/AGNOM...
9,KUR1,NSGA2,500000,50000000,2,5,[-5.05 -5.05 -5.05 -5.05 -5.05],[5. 5. 5. 5. 5.],5584.012155,[-2.88709264e+01 4.85385575e-10],100,100,/home/582/ow6835/MOOP/Result/KUR1/NSGA2_KUR1_5...,/home/582/ow6835/MOOP/Result/Images/KUR1/NSGA2...
10,KUR1,AGNOMEN,500000,50000000,2,3,[-5.05 -5.05 -5.05],[5. 5. 5.],12744.641698,[-1.44369421e+01 3.36475393e-11],100,100,/home/582/ow6835/MOOP/Result/KUR1/AGNOMEN_KUR1...,/home/582/ow6835/MOOP/Result/Images/KUR1/AGNOM...
11,KUR1,NSGA2,500000,50000000,2,4,[-5.05 -5.05 -5.05 -5.05],[5. 5. 5. 5.],5066.205252,[-2.16531949e+01 3.13770943e-10],100,100,/home/582/ow6835/MOOP/Result/KUR1/NSGA2_KUR1_4...,/home/582/ow6835/MOOP/Result/Images/KUR1/NSGA2...
12,KUR1,RNSGA2,500000,50000000,2,4,[-5.05 -5.05 -5.05 -5.05],[5. 5. 5. 5.],8728.917754,[-21.65319538 -3.35967902],100,100,/home/582/ow6835/MOOP/Result/KUR1/RNSGA2_KUR1_...,/home/582/ow6835/MOOP/Result/Images/KUR1/RNSGA...
13,KUR1,RNSGA2,500000,50000000,2,3,[-5.05 -5.05 -5.05],[5. 5. 5.],8821.296392,[-14.43546358 -4.01081182],100,100,/home/582/ow6835/MOOP/Result/KUR1/RNSGA2_KUR1_...,/home/582/ow6835/MOOP/Result/Images/KUR1/RNSGA...
14,KUR1,NSGA2,500000,50000000,2,2,[-5.05 -5.05],[5. 5.],5227.832469,[-7.21773196e+00 7.99402339e-11],100,100,/home/582/ow6835/MOOP/Result/KUR1/NSGA2_KUR1_2...,/home/582/ow6835/MOOP/Result/Images/KUR1/NSGA2...
15,KUR1,NSGA2,500000,50000000,2,3,[-5.05 -5.05 -5.05],[5. 5. 5.],4989.603527,[-1.44354640e+01 3.96615413e-11],100,100,/home/582/ow6835/MOOP/Result/KUR1/NSGA2_KUR1_3...,/home/582/ow6835/MOOP/Result/Images/KUR1/NSGA2...
16,LTDZ1,AGNOMEN,500000,50000000,3,3,[0 0 0],[1 1 1],21638.296182,[-1.91568239 -1.92996383 -2. ],100,100,/home/582/ow6835/MOOP/Result/LTDZ1/AGNOMEN_LTD...,/home/582/ow6835/MOOP/Result/Images/LTDZ1/AGNO...
17,LTDZ1,NSGA3,500000,50000000,3,3,[0 0 0],[1 1 1],6873.006294,[-2.00342476 -2.0003525 -1.97836511],141,100,/home/582/ow6835/MOOP/Result/LTDZ1/NSGA3_LTDZ1...,/home/582/ow6835/MOOP/Result/Images/LTDZ1/NSGA...
18,LTDZ1,NSGA2,500000,50000000,3,3,[0 0 0],[1 1 1],5265.761992,[-2. -2. -2.],100,100,/home/582/ow6835/MOOP/Result/LTDZ1/NSGA2_LTDZ1...,/home/582/ow6835/MOOP/Result/Images/LTDZ1/NSGA...
19,LTDZ1,RNSGA2,500000,50000000,3,3,[0 0 0],[1 1 1],11255.211650,[-2.25455573 -2.21312636 -2.39012684],100,100,/home/582/ow6835/MOOP/Result/LTDZ1/RNSGA2_LTDZ...,/home/582/ow6835/MOOP/Result/Images/LTDZ1/RNSG...
20,SK2,AGNOMEN,500000,50000000,2,4,[-10. -10. -10. -10.],[10. 10. 10. 10.],12809.775975,[34.15185502 0.61529185],100,100,/home/582/ow6835/MOOP/Result/SK2/AGNOMEN_SK2_4...,/home/582/ow6835/MOOP/Result/Images/SK2/AGNOME...
21,SK2,NSGA3,500000,50000000,2,4,[-10. -10. -10. -10.],[10. 10. 10. 10.],5926.211479,[11.32957953 -0.12183005],121,100,/home/582/ow6835/MOOP/Result/SK2/NSGA3_SK2_4/S...,/home/582/ow6835/MOOP/Result/Images/SK2/NSGA3_...
22,SK2,NSGA2,500000,50000000,2,4,[-10. -10. -10. -10.],[10. 10. 10. 10.],4870.022122,[34.1518613 0.61529145],100,100,/home/582/ow6835/MOOP/Result/SK2/NSGA2_SK2_4/S...,/home/582/ow6835/MOOP/Result/Images/SK2/NSGA2_...
23,SK2,RNSGA2,500000,50000000,2,4,[-10. -10. -10. -10.],[10. 10. 10. 10.],9412.824440,[1.0289498 0.61551304],100,100,/home/582/ow6835/MOOP/Result/SK2/RNSGA2_SK2_4/...,/home/582/ow6835/MOOP/Result/Images/SK2/RNSGA2...
24,SK2_TYPO,AGNOMEN,500000,50000000,2,4,[-10. -10. -10. -10.],[10. 10. 10. 10.],12959.943039,[16.59132326 0.43201899],100,100,/home/582/ow6835/MOOP/Result/SK2_TYPO/AGNOMEN_...,/home/582/ow6835/MOOP/Result/Images/SK2_TYPO/A...
25,SK2_TYPO,NSGA2,500000,50000000,2,4,[-10. -10. -10. -10.],[10. 10. 10. 10.],4865.705191,[16.59131401 0.43201723],100,100,/home/582/ow6835/MOOP/Result/SK2_TYPO/NSGA2_SK...,/home/582/ow6835/MOOP/Result/Images/SK2_TYPO/N...
26,SK2_TYPO,NSGA3,500000,50000000,2,4,[-10. -10. -10. -10.],[10. 10. 10. 10.],6001.223501,[15.39995446 0.09287089],120,100,/home/582/ow6835/MOOP/Result/SK2_TYPO/NSGA3_SK...,/home/582/ow6835/MOOP/Result/Images/SK2_TYPO/N...
27,SK2_TYPO,RNSGA2,500000,50000000,2,4,[-10. -10. -10. -10.],[10. 10. 10. 10.],9272.065241,[0.64880257 0.43201903],100,100,/home/582/ow6835/MOOP/Result/SK2_TYPO/RNSGA2_S...,/home/582/ow6835/MOOP/Result/Images/SK2_TYPO/R...
28,TKLY1,NSGA3,500000,50000000,2,4,[0 0 0 0],[1 1 1 1],6295.260294,[ 0.84572261 14.46610741],121,100,/home/582/ow6835/MOOP/Result/TKLY1/NSGA3_TKLY1...,/home/582/ow6835/MOOP/Result/Images/TKLY1/NSGA...
29,TKLY1,RNSGA2,500000,50000000,2,4,[0 0 0 0],[1 1 1 1],10122.678001,[1.08899342 2.86108362],100,100,/home/582/ow6835/MOOP/Result/TKLY1/RNSGA2_TKLY...,/home/582/ow6835/MOOP/Result/Images/TKLY1/RNSG...
30,TKLY1,NSGA2,500000,50000000,2,4,[0 0 0 0],[1 1 1 1],5015.728100,[ 1.1 14.1890026],100,100,/home/582/ow6835/MOOP/Result/TKLY1/NSGA2_TKLY1...,/home/582/ow6835/MOOP/Result/Images/TKLY1/NSGA...
31,TKLY1,AGNOMEN,500000,50000000,2,4,[0 0 0 0],[1 1 1 1],15038.398105,[ 1.09999915 14.1890026 ],100,100,/home/582/ow6835/MOOP/Result/TKLY1/AGNOMEN_TKL...,/home/582/ow6835/MOOP/Result/Images/TKLY1/AGNO...
32,VU1,RNSGA2,500000,50000000,2,2,[-3. -3.],[3. 3.],10644.564530,[0.99543653 4.89848851],100,100,/home/582/ow6835/MOOP/Result/VU1/RNSGA2_VU1_2/...,/home/582/ow6835/MOOP/Result/Images/VU1/RNSGA2...
33,VU1,NSGA3,500000,50000000,2,2,[-3. -3.],[3. 3.],6670.053805,[ 0.99437543 25.6866863 ],139,100,/home/582/ow6835/MOOP/Result/VU1/NSGA3_VU1_2/V...,/home/582/ow6835/MOOP/Result/Images/VU1/NSGA3_...
34,VU1,AGNOMEN,500000,50000000,2,2,[-3. -3.],[3. 3.],17299.870161,[ 1. 37.],100,100,/home/582/ow6835/MOOP/Result/VU1/AGNOMEN_VU1_2...,/home/582/ow6835/MOOP/Result/Images/VU1/AGNOME...
35,VU1,NSGA2,500000,50000000,2,2,[-3. -3.],[3. 3.],5199.784480,[ 1. 37.],100,100,/home/582/ow6835/MOOP/Result/VU1/NSGA2_VU1_2/V...,/home/582/ow6835/MOOP/Result/Images/VU1/NSGA2_...
36,VU2,AGNOMEN,500000,50000000,2,2,[-3. -3.],[3. 3.],19164.392457,[-2.00000002 2. ],100,100,/home/582/ow6835/MOOP/Result/VU2/AGNOMEN_VU2_2...,/home/582/ow6835/MOOP/Result/Images/VU2/AGNOME...
37,VU2,NSGA3,500000,50000000,2,2,[-3. -3.],[3. 3.],6653.263739,[-2.03886021 1.93850568],139,100,/home/582/ow6835/MOOP/Result/VU2/NSGA3_VU2_2/V...,/home/582/ow6835/MOOP/Result/Images/VU2/NSGA3_...
38,VU2,NSGA2,500000,50000000,2,2,[-3. -3.],[3. 3.],5254.906234,[-2.00000002 2. ],100,100,/home/582/ow6835/MOOP/Result/VU2/NSGA2_VU2_2/V...,/home/582/ow6835/MOOP/Result/Images/VU2/NSGA2_...
39,VU2,RNSGA2,500000,50000000,2,2,[-3. -3.],[3. 3.],9956.575833,[-2.00000002 -4.28506179],100,100,/home/582/ow6835/MOOP/Result/VU2/RNSGA2_VU2_2/...,/home/582/ow6835/MOOP/Result/Images/VU2/RNSGA2...
40,ZDT1,NSGA2,500000,50000000,2,10,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.],[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.],5007.286016,[1. 1.],100,100,/home/582/ow6835/MOOP/Result/ZDT1/NSGA2_ZDT1_1...,/home/582/ow6835/MOOP/Result/Images/ZDT1/NSGA2...
41,ZDT2,NSGA2,500000,50000000,2,10,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.],[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.],5617.633180,[1. 1.],100,100,/home/582/ow6835/MOOP/Result/ZDT2/NSGA2_ZDT2_1...,/home/582/ow6835/MOOP/Result/Images/ZDT2/NSGA2...
42,ZDT3,NSGA2,500000,50000000,2,10,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.],[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.],5188.160075,[0.85183289 1. ],100,100,/home/582/ow6835/MOOP/Result/ZDT3/NSGA2_ZDT3_1...,/home/582/ow6835/MOOP/Result/Images/ZDT3/NSGA2...

In [5]:
df.loc[df['Problem'] =='KUR1'].reset_index(drop=True)

,Problem,Alg_name,Iteration,Evaluations,Objectives,n_variables,xl,xu,exec_time,approx_nadir,solutions_shape,pop_size,path,image_location
0,KUR1,AGNOMEN,500000,50000000,2,2,[-5.05 -5.05],[5. 5.],13581.180147,[-7.21736514e+00 2.18325861e-11],100,100,/home/582/ow6835/MOOP/Result/KUR1/AGNOMEN_KUR1...,/home/582/ow6835/MOOP/Result/Images/KUR1/AGNOM...
1,KUR1,AGNOMEN,500000,50000000,2,3,[-5.05 -5.05 -5.05],[5. 5. 5.],12744.641698,[-1.44369421e+01 3.36475393e-11],100,100,/home/582/ow6835/MOOP/Result/KUR1/AGNOMEN_KUR1...,/home/582/ow6835/MOOP/Result/Images/KUR1/AGNOM...
2,KUR1,AGNOMEN,500000,50000000,2,4,[-5.05 -5.05 -5.05 -5.05],[5. 5. 5. 5.],14054.189155,[-2.16531951e+01 1.12373815e-07],100,100,/home/582/ow6835/MOOP/Result/KUR1/AGNOMEN_KUR1...,/home/582/ow6835/MOOP/Result/Images/KUR1/AGNOM...
3,KUR1,AGNOMEN,500000,50000000,2,5,[-5.05 -5.05 -5.05 -5.05 -5.05],[5. 5. 5. 5. 5.],12762.316965,[-2.88707639e+01 1.23197724e-07],100,100,/home/582/ow6835/MOOP/Result/KUR1/AGNOMEN_KUR1...,/home/582/ow6835/MOOP/Result/Images/KUR1/AGNOM...
4,KUR1,NSGA2,500000,50000000,2,2,[-5.05 -5.05],[5. 5.],5227.832469,[-7.21773196e+00 7.99402339e-11],100,100,/home/582/ow6835/MOOP/Result/KUR1/NSGA2_KUR1_2...,/home/582/ow6835/MOOP/Result/Images/KUR1/NSGA2...
5,KUR1,NSGA2,500000,50000000,2,3,[-5.05 -5.05 -5.05],[5. 5. 5.],4989.603527,[-1.44354640e+01 3.96615413e-11],100,100,/home/582/ow6835/MOOP/Result/KUR1/NSGA2_KUR1_3...,/home/582/ow6835/MOOP/Result/Images/KUR1/NSGA2...
6,KUR1,NSGA2,500000,50000000,2,4,[-5.05 -5.05 -5.05 -5.05],[5. 5. 5. 5.],5066.205252,[-2.16531949e+01 3.13770943e-10],100,100,/home/582/ow6835/MOOP/Result/KUR1/NSGA2_KUR1_4...,/home/582/ow6835/MOOP/Result/Images/KUR1/NSGA2...
7,KUR1,NSGA2,500000,50000000,2,5,[-5.05 -5.05 -5.05 -5.05 -5.05],[5. 5. 5. 5. 5.],5584.012155,[-2.88709264e+01 4.85385575e-10],100,100,/home/582/ow6835/MOOP/Result/KUR1/NSGA2_KUR1_5...,/home/582/ow6835/MOOP/Result/Images/KUR1/NSGA2...
8,KUR1,NSGA3,500000,50000000,2,2,[-5.05 -5.05],[5. 5.],6235.473179,[-7.22973258 0.07657397],117,100,/home/582/ow6835/MOOP/Result/KUR1/NSGA3_KUR1_2...,/home/582/ow6835/MOOP/Result/Images/KUR1/NSGA3...
9,KUR1,NSGA3,500000,50000000,2,3,[-5.05 -5.05 -5.05],[5. 5. 5.],6052.496338,[-14.64511541 -0.73148266],115,100,/home/582/ow6835/MOOP/Result/KUR1/NSGA3_KUR1_3...,/home/582/ow6835/MOOP/Result/Images/KUR1/NSGA3...
10,KUR1,NSGA3,500000,50000000,2,4,[-5.05 -5.05 -5.05 -5.05],[5. 5. 5. 5.],5977.766732,[-21.83803518 -0.60301657],114,100,/home/582/ow6835/MOOP/Result/KUR1/NSGA3_KUR1_4...,/home/582/ow6835/MOOP/Result/Images/KUR1/NSGA3...
11,KUR1,NSGA3,500000,50000000,2,5,[-5.05 -5.05 -5.05 -5.05 -5.05],[5. 5. 5. 5. 5.],5928.328999,[-29.29296344 -7.14727163],110,100,/home/582/ow6835/MOOP/Result/KUR1/NSGA3_KUR1_5...,/home/582/ow6835/MOOP/Result/Images/KUR1/NSGA3...
12,KUR1,RNSGA2,500000,50000000,2,2,[-5.05 -5.05],[5. 5.],9120.287959,[-7.21773178 -1.67613402],100,100,/home/582/ow6835/MOOP/Result/KUR1/RNSGA2_KUR1_...,/home/582/ow6835/MOOP/Result/Images/KUR1/RNSGA...
13,KUR1,RNSGA2,500000,50000000,2,3,[-5.05 -5.05 -5.05],[5. 5. 5.],8821.296392,[-14.43546358 -4.01081182],100,100,/home/582/ow6835/MOOP/Result/KUR1/RNSGA2_KUR1_...,/home/582/ow6835/MOOP/Result/Images/KUR1/RNSGA...
14,KUR1,RNSGA2,500000,50000000,2,4,[-5.05 -5.05 -5.05 -5.05],[5. 5. 5. 5.],8728.917754,[-21.65319538 -3.35967902],100,100,/home/582/ow6835/MOOP/Result/KUR1/RNSGA2_KUR1_...,/home/582/ow6835/MOOP/Result/Images/KUR1/RNSGA...
15,KUR1,RNSGA2,500000,50000000,2,5,[-5.05 -5.05 -5.05 -5.05 -5.05],[5. 5. 5. 5. 5.],8727.708246,[-28.87092719 -11.90693593],100,100,/home/582/ow6835/MOOP/Result/KUR1/RNSGA2_KUR1_...,/home/582/ow6835/MOOP/Result/Images/KUR1/RNSGA...

In [6]:
df.loc[df['Problem'] =='VU1'].reset_index(drop=True)

,Problem,Alg_name,Iteration,Evaluations,Objectives,n_variables,xl,xu,exec_time,approx_nadir,solutions_shape,pop_size,path,image_location
0,VU1,AGNOMEN,500000,50000000,2,2,[-3. -3.],[3. 3.],17299.870161,[ 1. 37.],100,100,/home/582/ow6835/MOOP/Result/VU1/AGNOMEN_VU1_2...,/home/582/ow6835/MOOP/Result/Images/VU1/AGNOME...
1,VU1,NSGA2,500000,50000000,2,2,[-3. -3.],[3. 3.],5199.784480,[ 1. 37.],100,100,/home/582/ow6835/MOOP/Result/VU1/NSGA2_VU1_2/V...,/home/582/ow6835/MOOP/Result/Images/VU1/NSGA2_...
2,VU1,NSGA3,500000,50000000,2,2,[-3. -3.],[3. 3.],6670.053805,[ 0.99437543 25.6866863 ],139,100,/home/582/ow6835/MOOP/Result/VU1/NSGA3_VU1_2/V...,/home/582/ow6835/MOOP/Result/Images/VU1/NSGA3_...
3,VU1,RNSGA2,500000,50000000,2,2,[-3. -3.],[3. 3.],10644.564530,[0.99543653 4.89848851],100,100,/home/582/ow6835/MOOP/Result/VU1/RNSGA2_VU1_2/...,/home/582/ow6835/MOOP/Result/Images/VU1/RNSGA2...

In [7]:
df.loc[df['Problem'] =='VU2'].reset_index(drop=True)

,Problem,Alg_name,Iteration,Evaluations,Objectives,n_variables,xl,xu,exec_time,approx_nadir,solutions_shape,pop_size,path,image_location
0,VU2,AGNOMEN,500000,50000000,2,2,[-3. -3.],[3. 3.],19164.392457,[-2.00000002 2. ],100,100,/home/582/ow6835/MOOP/Result/VU2/AGNOMEN_VU2_2...,/home/582/ow6835/MOOP/Result/Images/VU2/AGNOME...
1,VU2,NSGA2,500000,50000000,2,2,[-3. -3.],[3. 3.],5254.906234,[-2.00000002 2. ],100,100,/home/582/ow6835/MOOP/Result/VU2/NSGA2_VU2_2/V...,/home/582/ow6835/MOOP/Result/Images/VU2/NSGA2_...
2,VU2,NSGA3,500000,50000000,2,2,[-3. -3.],[3. 3.],6653.263739,[-2.03886021 1.93850568],139,100,/home/582/ow6835/MOOP/Result/VU2/NSGA3_VU2_2/V...,/home/582/ow6835/MOOP/Result/Images/VU2/NSGA3_...
3,VU2,RNSGA2,500000,50000000,2,2,[-3. -3.],[3. 3.],9956.575833,[-2.00000002 -4.28506179],100,100,/home/582/ow6835/MOOP/Result/VU2/RNSGA2_VU2_2/...,/home/582/ow6835/MOOP/Result/Images/VU2/RNSGA2...

In [8]:

df.loc[df['Problem'] =='TKLY1'].reset_index(drop=True)

,Problem,Alg_name,Iteration,Evaluations,Objectives,n_variables,xl,xu,exec_time,approx_nadir,solutions_shape,pop_size,path,image_location
0,TKLY1,AGNOMEN,500000,50000000,2,4,[0 0 0 0],[1 1 1 1],15038.398105,[ 1.09999915 14.1890026 ],100,100,/home/582/ow6835/MOOP/Result/TKLY1/AGNOMEN_TKL...,/home/582/ow6835/MOOP/Result/Images/TKLY1/AGNO...
1,TKLY1,NSGA2,500000,50000000,2,4,[0 0 0 0],[1 1 1 1],5015.728100,[ 1.1 14.1890026],100,100,/home/582/ow6835/MOOP/Result/TKLY1/NSGA2_TKLY1...,/home/582/ow6835/MOOP/Result/Images/TKLY1/NSGA...
2,TKLY1,NSGA3,500000,50000000,2,4,[0 0 0 0],[1 1 1 1],6295.260294,[ 0.84572261 14.46610741],121,100,/home/582/ow6835/MOOP/Result/TKLY1/NSGA3_TKLY1...,/home/582/ow6835/MOOP/Result/Images/TKLY1/NSGA...
3,TKLY1,RNSGA2,500000,50000000,2,4,[0 0 0 0],[1 1 1 1],10122.678001,[1.08899342 2.86108362],100,100,/home/582/ow6835/MOOP/Result/TKLY1/RNSGA2_TKLY...,/home/582/ow6835/MOOP/Result/Images/TKLY1/RNSG...

In [9]:
df.loc[df['Problem'] =='LTDZ1'].reset_index(drop=True)

,Problem,Alg_name,Iteration,Evaluations,Objectives,n_variables,xl,xu,exec_time,approx_nadir,solutions_shape,pop_size,path,image_location
0,LTDZ1,AGNOMEN,500000,50000000,3,3,[0 0 0],[1 1 1],21638.296182,[-1.91568239 -1.92996383 -2. ],100,100,/home/582/ow6835/MOOP/Result/LTDZ1/AGNOMEN_LTD...,/home/582/ow6835/MOOP/Result/Images/LTDZ1/AGNO...
1,LTDZ1,NSGA2,500000,50000000,3,3,[0 0 0],[1 1 1],5265.761992,[-2. -2. -2.],100,100,/home/582/ow6835/MOOP/Result/LTDZ1/NSGA2_LTDZ1...,/home/582/ow6835/MOOP/Result/Images/LTDZ1/NSGA...
2,LTDZ1,NSGA3,500000,50000000,3,3,[0 0 0],[1 1 1],6873.006294,[-2.00342476 -2.0003525 -1.97836511],141,100,/home/582/ow6835/MOOP/Result/LTDZ1/NSGA3_LTDZ1...,/home/582/ow6835/MOOP/Result/Images/LTDZ1/NSGA...
3,LTDZ1,RNSGA2,500000,50000000,3,3,[0 0 0],[1 1 1],11255.211650,[-2.25455573 -2.21312636 -2.39012684],100,100,/home/582/ow6835/MOOP/Result/LTDZ1/RNSGA2_LTDZ...,/home/582/ow6835/MOOP/Result/Images/LTDZ1/RNSG...

In [10]:
df.loc[df['Problem'] =='SK2'].reset_index(drop=True)

,Problem,Alg_name,Iteration,Evaluations,Objectives,n_variables,xl,xu,exec_time,approx_nadir,solutions_shape,pop_size,path,image_location
0,SK2,AGNOMEN,500000,50000000,2,4,[-10. -10. -10. -10.],[10. 10. 10. 10.],12809.775975,[34.15185502 0.61529185],100,100,/home/582/ow6835/MOOP/Result/SK2/AGNOMEN_SK2_4...,/home/582/ow6835/MOOP/Result/Images/SK2/AGNOME...
1,SK2,NSGA2,500000,50000000,2,4,[-10. -10. -10. -10.],[10. 10. 10. 10.],4870.022122,[34.1518613 0.61529145],100,100,/home/582/ow6835/MOOP/Result/SK2/NSGA2_SK2_4/S...,/home/582/ow6835/MOOP/Result/Images/SK2/NSGA2_...
2,SK2,NSGA3,500000,50000000,2,4,[-10. -10. -10. -10.],[10. 10. 10. 10.],5926.211479,[11.32957953 -0.12183005],121,100,/home/582/ow6835/MOOP/Result/SK2/NSGA3_SK2_4/S...,/home/582/ow6835/MOOP/Result/Images/SK2/NSGA3_...
3,SK2,RNSGA2,500000,50000000,2,4,[-10. -10. -10. -10.],[10. 10. 10. 10.],9412.824440,[1.0289498 0.61551304],100,100,/home/582/ow6835/MOOP/Result/SK2/RNSGA2_SK2_4/...,/home/582/ow6835/MOOP/Result/Images/SK2/RNSGA2...

In [11]:
df.loc[df['Problem'] =='SK2_TYPO'].reset_index(drop=True)

,Problem,Alg_name,Iteration,Evaluations,Objectives,n_variables,xl,xu,exec_time,approx_nadir,solutions_shape,pop_size,path,image_location
0,SK2_TYPO,AGNOMEN,500000,50000000,2,4,[-10. -10. -10. -10.],[10. 10. 10. 10.],12959.943039,[16.59132326 0.43201899],100,100,/home/582/ow6835/MOOP/Result/SK2_TYPO/AGNOMEN_...,/home/582/ow6835/MOOP/Result/Images/SK2_TYPO/A...
1,SK2_TYPO,NSGA2,500000,50000000,2,4,[-10. -10. -10. -10.],[10. 10. 10. 10.],4865.705191,[16.59131401 0.43201723],100,100,/home/582/ow6835/MOOP/Result/SK2_TYPO/NSGA2_SK...,/home/582/ow6835/MOOP/Result/Images/SK2_TYPO/N...
2,SK2_TYPO,NSGA3,500000,50000000,2,4,[-10. -10. -10. -10.],[10. 10. 10. 10.],6001.223501,[15.39995446 0.09287089],120,100,/home/582/ow6835/MOOP/Result/SK2_TYPO/NSGA3_SK...,/home/582/ow6835/MOOP/Result/Images/SK2_TYPO/N...
3,SK2_TYPO,RNSGA2,500000,50000000,2,4,[-10. -10. -10. -10.],[10. 10. 10. 10.],9272.065241,[0.64880257 0.43201903],100,100,/home/582/ow6835/MOOP/Result/SK2_TYPO/RNSGA2_S...,/home/582/ow6835/MOOP/Result/Images/SK2_TYPO/R...

In [13]:
df.loc[df['Problem'] =='ZDT1'].reset_index(drop=True)

,Problem,Alg_name,Iteration,Evaluations,Objectives,n_variables,xl,xu,exec_time,approx_nadir,solutions_shape,pop_size,path,image_location
0,ZDT1,NSGA2,500000,50000000,2,10,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.],[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.],5007.286016,[1. 1.],100,100,/home/582/ow6835/MOOP/Result/ZDT1/NSGA2_ZDT1_1...,/home/582/ow6835/MOOP/Result/Images/ZDT1/NSGA2...

In [14]:
df.loc[df['Problem'] =='ZDT2'].reset_index(drop=True)

,Problem,Alg_name,Iteration,Evaluations,Objectives,n_variables,xl,xu,exec_time,approx_nadir,solutions_shape,pop_size,path,image_location
0,ZDT2,NSGA2,500000,50000000,2,10,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.],[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.],5617.63318,[1. 1.],100,100,/home/582/ow6835/MOOP/Result/ZDT2/NSGA2_ZDT2_1...,/home/582/ow6835/MOOP/Result/Images/ZDT2/NSGA2...

In [15]:
df.loc[df['Problem'] =='ZDT3'].reset_index(drop=True)

,Problem,Alg_name,Iteration,Evaluations,Objectives,n_variables,xl,xu,exec_time,approx_nadir,solutions_shape,pop_size,path,image_location
0,ZDT3,NSGA2,500000,50000000,2,10,[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.],[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.],5188.160075,[0.85183289 1. ],100,100,/home/582/ow6835/MOOP/Result/ZDT3/NSGA2_ZDT3_1...,/home/582/ow6835/MOOP/Result/Images/ZDT3/NSGA2...

In [1]:
import requests 
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import NoSuchElementException
from time import sleep

In [10]:
search_input = 'Jianxin' +' Deakin'

driver = webdriver.Chrome()
driver.get("https://scholar.google.com")
#google schloar seach input
#search = driver.find_element_by_id('gs_hdr_tsi')
search = driver.find_element_by_css_selector('input[name= "q"]')

search.send_keys(search_input)# search professor name
search.send_keys(Keys.RETURN) #return result
sleep(5)
#if professor has profile page

try:
    profile_url = driver.find_element_by_css_selector('h4.gs_rt2>a').get_attribute('href')
    driver.get(profile_url) # get profile page
    sleep(5)
    #use soup to get content on profile page
    webpage_response = requests.get(profile_url, 'html.parsers')
    webpage = BeautifulSoup(webpage_response.content, "html.parser")
    #get citation information and store in list
    citation = [i.string for i in webpage.find_all('td', {'class':"gsc_rsb_std"})]
    
#if professor has no such profile page
except NoSuchElementException:
    citation = ['na' for i in range(6)] 
    pass
print(citation)

/var/folders/tc/s1vsgctn4gn_n76ylgwmdwrw0000gn/T/ipykernel_13347/3319657275.py:7: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  search = driver.find_element_by_css_selector('input[name= "q"]')
/var/folders/tc/s1vsgctn4gn_n76ylgwmdwrw0000gn/T/ipykernel_13347/3319657275.py:15: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  profile_url = driver.find_element_by_css_selector('h4.gs_rt2>a').get_attribute('href')

['1833', '1455', '23', '20', '48', '42']